/**
 * PrimeNG icon constants used throughout the application
 */
export const ICONS = {
  COMMON: {
    HOME: 'pi pi-home',
    LIST: 'pi pi-list',
    ADD: 'pi pi-plus-circle',
    PLUS: 'pi pi-plus',
    MANUAL: 'pi pi-exclamation-triangle',
    SYNC: 'pi pi-sync',
    BOOK: 'pi pi-book',
    CHART: 'pi pi-chart-bar',
    CHART_PIE: 'pi pi-chart-pie',
    FILE: 'pi pi-file',
    ARROW_UP: 'pi pi-arrow-up',
    SITEMAP: 'pi pi-sitemap',
    SEARCH: 'pi pi-search',
    INFO_CIRCLE: 'pi pi-info-circle',
    CHEVRON_DOWN: 'pi pi-chevron-down',
    TH_LARGE: 'pi pi-th-large',
    VIEW: 'pi pi-eye',
    WINDOW_MAXIMIZE: 'pi pi-window-maximize',
    DOWNLOAD: 'pi pi-download',
  },
  MEDIA: {
    PDF: 'pi pi-file-pdf',
    DOCUMENT: 'pi pi-file-word',
    SPREADSHEET: 'pi pi-file-excel',
    PRESENTATION: 'pi pi-file',
    VIDEO: 'pi pi-video',
    AUDIO: 'pi pi-volume-up',
    ARCHIVE: 'pi pi-file',
    UNSUPPORTED: 'pi pi-file',
    IMAGE: 'pi pi-image',
  },
  ACTIONS: {
    CHECK: 'pi pi-check',
    CHECK_CIRCLE: 'pi pi-check-circle',
    TIMES: 'pi pi-times',
    PENCIL: 'pi pi-pencil',
    EDIT: 'pi pi-pencil',
    TRASH: 'pi pi-trash',
    EYE: 'pi pi-eye',
    BAN: 'pi pi-ban',
    POWER_OFF: 'pi pi-power-off',
  },
  EMPLOYEE: {
    GROUP: 'pi pi-users',
    USER: 'pi pi-user',
    ADD_USER: 'pi pi-user-plus',
    REMOVE_USER: 'pi pi-user-minus',
    EDIT_USER: 'pi pi-user-edit',
  },
  ATTENDANCE: {
    CALENDAR: 'pi pi-calendar',
    CHECK: 'pi pi-check-square',
    FORCE: 'pi pi-user-edit',
    REGULARIZE: 'pi pi-clock',
  },
  EXPENSE: {
    MONEY: 'pi pi-money-bill',
    CAR: 'pi pi-car',
  },
  LEAVE: {
    GET: 'pi pi-calendar-minus',
    PLUS: 'pi pi-plus',
    FORCE: 'pi pi-user-edit',
  },
  ASSET: {
    BOX: 'pi pi-box',
    CARD: 'pi pi-credit-card',
    CAR: 'pi pi-car',
  },
  PAYROLL: {
    WALLET: 'pi pi-wallet',
  },
  SITE: {
    BUILDING: 'pi pi-building',
  },
  SECURITY: {
    SHIELD: 'pi pi-shield',
    KEY: 'pi pi-key',
    LOCK: 'pi pi-lock',
    UNLOCK: 'pi pi-unlock',
  },
  SETTINGS: {
    COG: 'pi pi-cog',
    SLIDERS: 'pi pi-sliders-h',
    WRENCH: 'pi pi-wrench',
  },
  THEME: {
    MOON: 'pi pi-moon',
  },
} as const;
