/**
 * PrimeNG icon constants used throughout the application
 */
export const ICONS = {
  COMMON: {
    HOME: 'pi pi-home',
    LIST: 'pi pi-list',
    ADD: 'pi pi-plus-circle',
    PLUS: 'pi pi-plus',
    MANUAL: 'pi pi-exclamation-triangle',
    SYNC: 'pi pi-sync',
    BOOK: 'pi pi-book',
    CHART: 'pi pi-chart-bar',
    CHART_PIE: 'pi pi-chart-pie',
    FILE: 'pi pi-file',
    ARROW_UP: 'pi pi-arrow-up',
    ARROW_DOWN: 'pi pi-arrow-down',
    SITEMAP: 'pi pi-sitemap',
    SEARCH: 'pi pi-search',
    INFO_CIRCLE: 'pi pi-info-circle',
    CHEVRON_DOWN: 'pi pi-chevron-down',
    CHEVRON_RIGHT: 'pi pi-chevron-right',
    TH_LARGE: 'pi pi-th-large',
    VIEW: 'pi pi-info-circle',
    WINDOW_MAXIMIZE: 'pi pi-window-maximize',
    DOWNLOAD: 'pi pi-download',
    MAP_MARKER: 'pi pi-map-marker',
    USER: 'pi pi-user',
    USERS: 'pi pi-users',
    CAR: 'pi pi-car',
    FORCE: 'pi pi-user-edit',
    PAPERCLIP: 'pi pi-paperclip',
    CLOUD_UPLOAD: 'pi pi-cloud-upload',
    ARROW_RIGHT: 'pi pi-arrow-right',
    ARROW_LEFT: 'pi pi-arrow-left',
    GIFT: 'pi pi-gift',
    PHONE: 'pi pi-phone',
    BRIEFCASE: 'pi pi-briefcase',
    CREDIT_CARD: 'pi pi-credit-card',
    ID_CARD: 'pi pi-id-card',
    EMAIL: 'pi pi-envelope',
    CALENDAR: 'pi pi-calendar',
    TOGGLE: 'pi pi-android',
    WIFI: 'pi pi-wifi',
    WIFI_SLASH: 'pi pi-wifi-slash',
    SPINNER: 'pi pi-spinner',
    SPIN: 'pi pi-spin',
    EXCLAMATION_TRIANGLE: 'pi pi-exclamation-triangle',
    HISTORY: 'pi pi-history',
  },
  MEDIA: {
    PDF: 'pi pi-file-pdf',
    DOCUMENT: 'pi pi-file-word',
    SPREADSHEET: 'pi pi-file-excel',
    PRESENTATION: 'pi pi-file',
    VIDEO: 'pi pi-video',
    AUDIO: 'pi pi-volume-up',
    ARCHIVE: 'pi pi-file',
    UNSUPPORTED: 'pi pi-file',
    IMAGE: 'pi pi-image',
  },
  ACTIONS: {
    CHECK: 'pi pi-check-circle',
    CHECK_CIRCLE: 'pi pi-check-circle',
    TIMES: 'pi pi-times-circle',
    PENCIL: 'pi pi-pencil',
    EDIT: 'pi pi-pencil',
    TRASH: 'pi pi-trash',
    EYE: 'pi pi-eye',
    BAN: 'pi pi-ban',
    POWER_OFF: 'pi pi-power-off',
    SEND: 'pi pi-send',
  },
  EMPLOYEE: {
    GROUP: 'pi pi-users',
    USER: 'pi pi-user',
    ADD_USER: 'pi pi-user-plus',
    REMOVE_USER: 'pi pi-user-minus',
    EDIT_USER: 'pi pi-user-edit',
  },
  ATTENDANCE: {
    CALENDAR: 'pi pi-calendar',
    CHECK: 'pi pi-check-square',
    REGULARIZE: 'pi pi-clock',
    CHECK_IN: 'pi pi-sign-in',
    CHECK_OUT: 'pi pi-sign-out',
  },
  EXPENSE: {
    MONEY: 'pi pi-money-bill',
    CAR: 'pi pi-car',
  },
  LEAVE: {
    GET: 'pi pi-calendar-minus',
    PLUS: 'pi pi-plus',
    FORCE: 'pi pi-user-edit',
  },
  ASSET: {
    BOX: 'pi pi-box',
    CARD: 'pi pi-credit-card',
    CAR: 'pi pi-car',
  },
  PAYROLL: {
    WALLET: 'pi pi-wallet',
    PAID: 'pi pi-check-circle',
    GENERATE: 'pi pi-file-edit',
  },
  SITE: {
    BUILDING: 'pi pi-building',
  },
  SECURITY: {
    SHIELD: 'pi pi-shield',
    KEY: 'pi pi-key',
    LOCK: 'pi pi-lock',
    UNLOCK: 'pi pi-unlock',
  },
  SETTINGS: {
    COG: 'pi pi-cog',
    SLIDERS: 'pi pi-sliders-h',
    WRENCH: 'pi pi-wrench',
  },
  THEME: {
    MOON: 'pi pi-moon',
    SUN: 'pi pi-sun',
  },
  // Common status icons for metrics/stats
  STATUS: {
    TOTAL: 'pi pi-list',
    AVAILABLE: 'pi pi-check-circle',
    ASSIGNED: 'pi pi-user',
    EXPIRING_SOON: 'pi pi-exclamation-triangle',
    EXPIRED: 'pi pi-times-circle',
  },
} as const;
