import { EUserRole } from '@shared/constants/role.constants';

/** Each UI permission must list every role; use with `UI_PERMISSIONS_ROLE_MAP`. */
export type UIRolePermissionAccess = Record<EUserRole, boolean>;

export const APP_PERMISSION = {
  ANNOUNCEMENT: {
    VIEW_DETAIL: 'view_detail_announcement',
    TABLE_VIEW: 'table_view_announcement',
    CARD_VIEW: 'card_view_announcement',
    ADD: 'add_announcement',
    EDIT: 'edit_announcement',
    DELETE: 'delete_announcement',
  },
  ASSET: {
    VIEW_DETAIL: 'view_detail_asset',
    TABLE_VIEW: 'table_view_asset',
    CARD_VIEW: 'card_view_asset',
    ADD: 'add_asset',
    EDIT: 'edit_asset',
    DELETE: 'delete_asset',
    HANDOVER_INITIATE: 'handover_initiate_asset',
    HANDOVER_ACCEPTED: 'handover_accepted_asset',
    HANDOVER_REJECTED: 'handover_rejected_asset',
    HANDOVER_CANCELLED: 'handover_cancelled_asset',
    DEALLOCATE: 'deallocate_asset',
    EVENT_HISTORY: 'event_history_asset',
  },
  ATTENDANCE: {
    VIEW_DETAIL: 'view_detail_attendance',
    TABLE_VIEW: 'table_view_attendance',
    CARD_VIEW: 'card_view_attendance',
    APPLY: 'apply_attendance',
    FORCE: 'force_attendance',
    REGULARIZE: 'regularize_attendance',
    APPROVE: 'approve_attendance',
    REJECT: 'reject_attendance',
  },
  COMPANY: {
    VIEW_DETAIL: 'view_detail_company',
    TABLE_VIEW: 'table_view_company',
    CARD_VIEW: 'card_view_company',
    ADD: 'add_company',
    EDIT: 'edit_company',
    DELETE: 'delete_company',
    CHANGE_STATUS: 'change_status_company',
  },
  CONTRACTOR: {
    VIEW_DETAIL: 'view_detail_contractor',
    TABLE_VIEW: 'table_view_contractor',
    CARD_VIEW: 'card_view_contractor',
    ADD: 'add_contractor',
    EDIT: 'edit_contractor',
    DELETE: 'delete_contractor',
    CHANGE_STATUS: 'change_status_contractor',
  },
  EMPLOYEE: {
    VIEW_DETAIL: 'view_detail_employee',
    TABLE_VIEW: 'table_view_employee',
    CARD_VIEW: 'card_view_employee',
    ADD: 'add_employee',
    EDIT: 'edit_employee',
    DELETE: 'delete_employee',
    CHANGE_STATUS: 'change_status_employee',
    SEND_PASSWORD_LINK: 'send_password_link_employee',
  },
  EXPENSE: {
    VIEW_DETAIL: 'view_detail_expense',
    TABLE_VIEW: 'table_view_expense',
    CARD_VIEW: 'card_view_expense',
    ADD: 'add_expense',
    EDIT: 'edit_expense',
    DELETE: 'delete_expense',
    FORCE: 'force_expense',
    REIMBURSE: 'reimburse_expense',
    APPROVE: 'approve_expense',
    REJECT: 'reject_expense',
  },
  FUEL_EXPENSE: {
    VIEW_DETAIL: 'view_detail_fuel',
    TABLE_VIEW: 'table_view_fuel',
    CARD_VIEW: 'card_view_fuel',
    ADD: 'add_fuel',
    EDIT: 'edit_fuel',
    DELETE: 'delete_fuel',
    FORCE: 'force_fuel',
    REIMBURSE: 'reimburse_fuel',
    APPROVE: 'approve_fuel',
    REJECT: 'reject_fuel',
  },
  LEAVE: {
    VIEW_DETAIL: 'view_detail_leave',
    TABLE_VIEW: 'table_view_leave',
    CARD_VIEW: 'card_view_leave',
    APPLY: 'apply_leave',
    FORCE: 'force_leave',
    APPROVE: 'approve_leave',
    REJECT: 'reject_leave',
    CANCEL: 'cancel_leave',
  },
  PAYROLL: {
    VIEW_DETAIL: 'view_detail_payroll',
    TABLE_VIEW: 'table_view_payroll',
    CARD_VIEW: 'card_view_payroll',
    PAID: 'paid_payslip_payroll',
    GENERATE_PAYSLIP: 'generate_payslip_payroll',
    GENERATE: 'generate_payroll_payroll',
    MONTHLY_REPORT: 'download_monthly_report_payroll',
    CANCEL: 'cancel_payslip_payroll',
    APPROVE: 'approve_payslip_payroll',
    ADD_INCREMENT: 'add_increment_payroll',
  },
  PETRO_CARD: {
    TABLE_VIEW: 'table_view_petro_card',
    CARD_VIEW: 'card_view_petro_card',
    ADD: 'add_petro_card',
    EDIT: 'edit_petro_card',
    DELETE: 'delete_petro_card',
    LINK_VEHICLE: 'link_vehicle_petro_card',
    UNLINK_VEHICLE: 'unlink_vehicle_petro_card',
  },
  PROJECT: {
    VIEW_DETAIL: 'view_detail_project',
    TABLE_VIEW: 'table_view_project',
    CARD_VIEW: 'card_view_project',
    ADD: 'add_project',
    EDIT: 'edit_project',
    DELETE: 'delete_project',
    CHANGE_STATUS: 'change_status_project',
    ANALYSIS: 'analysis_project',
    ALLOCATE_DEALLOCATE_EMPLOYEE: 'allocate_deallocate_employee_project',
  },
  ROLE_PERMISSION: {
    TABLE_VIEW: 'table_view_role_permission',
    CARD_VIEW: 'card_view_role_permission',
    ADD: 'add_role_permission',
    EDIT: 'edit_role_permission',
    DELETE: 'delete_role_permission',
    SET: 'set_permission_role_permission',
  },
  SALARY_STRUCTURE: {
    VIEW_DETAIL: 'view_detail_salary_structure',
    TABLE_VIEW: 'table_view_salary_structure',
    CARD_VIEW: 'card_view_salary_structure',
    EDIT: 'edit_salary_structure',
  },
  SYSTEM_PERMISSION: {
    TABLE_VIEW: 'table_view_system_permission',
    CARD_VIEW: 'card_view_system_permission',
    ADD: 'add_system_permission',
    EDIT: 'edit_system_permission',
    DELETE: 'delete_system_permission',
    SET: 'set_permission_system_permission',
  },
  USER_PERMISSION: {
    TABLE_VIEW: 'table_view_user_permission',
    CARD_VIEW: 'card_view_user_permission',
    DELETE: 'delete_user_permission',
    SET: 'set_permission_user_permission',
    CHANGE_ROLE: 'change_role_user_permission',
  },
  VEHICLE: {
    VIEW_DETAIL: 'view_detail_vehicle',
    TABLE_VIEW: 'table_view_vehicle',
    CARD_VIEW: 'card_view_vehicle',
    ADD: 'add_vehicle',
    EDIT: 'edit_vehicle',
    DELETE: 'delete_vehicle',
    HANDOVER_INITIATE: 'handover_initiate_vehicle',
    HANDOVER_ACCEPTED: 'handover_accepted_vehicle',
    HANDOVER_REJECTED: 'handover_rejected_vehicle',
    HANDOVER_CANCELLED: 'handover_cancelled_vehicle',
    DEALLOCATE: 'deallocate_vehicle',
    EVENT_HISTORY: 'event_history_vehicle',
    SERVICE_HISTORY: 'service_history_vehicle',
    LINK_PETRO_CARD: 'link_petro_card_vehicle',
    UNLINK_PETRO_CARD: 'unlink_petro_card_vehicle',
  },
  VEHICLE_READING: {
    VIEW_DETAIL: 'view_detail_vehicle_reading',
    TABLE_VIEW: 'table_view_vehicle_reading',
    CARD_VIEW: 'card_view_vehicle_reading',
    ADD: 'add_vehicle_reading',
    EDIT: 'edit_vehicle_reading',
    FORCE: 'force_vehicle_reading',
  },
  VEHICLE_SERVICE: {
    VIEW_DETAIL: 'view_detail_vehicle_service',
    TABLE_VIEW: 'table_view_vehicle_service',
    CARD_VIEW: 'card_view_vehicle_service',
    ADD: 'add_vehicle_service',
    EDIT: 'edit_vehicle_service',
    DELETE: 'delete_vehicle_service',
  },
  UI: {
    SALARY_STRUCTURE: {
      TABLE: 'ui_table_salary_structure',
      CONTACT_ANNEXURE: 'ui_contact_annexure_salary_structure',
    },
    COMMON: {
      SIDEBAR_INITIALS: 'ui_common_sidebar_initials',
    },
    ATTENDANCE: {
      TABLE_EMPLOYEE_NAME: 'ui_attendance_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_attendance_search_filter_employee_name',
    },
    EXPENSE: {
      TABLE_EMPLOYEE_NAME: 'ui_expense_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_expense_search_filter_employee_name',
    },
    LEAVE: {
      TABLE_EMPLOYEE_NAME: 'ui_leave_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_leave_search_filter_employee_name',
    },
    FUEL_EXPENSE: {
      TABLE_EMPLOYEE_NAME: 'ui_fuel_expense_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME:
        'ui_fuel_expense_search_filter_employee_name',
    },
    VEHICLE_READING: {
      SEARCH_FILTER_EMPLOYEE_NAME:
        'ui_vehicle_reading_search_filter_employee_name',
    },
    PAYROLL: {
      TABLE_EMPLOYEE_NAME: 'ui_payroll_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_payroll_search_filter_employee_name',
    },
    PROJECT: {
      SEARCH_FILTER_COMPANY_NAME: 'ui_project_search_filter_company_name',
      SEARCH_FILTER_CONTRACTOR_NAME: 'ui_project_search_filter_contractor_name',
    },
    PROJECT_ANALYSIS: {
      TIMELINE: 'ui_project_analysis_timeline',
      PROFITABILITY: 'ui_project_analysis_profitability',
      DOC: 'ui_project_analysis_doc',
      DSR: 'ui_project_analysis_dsr',
    },
    DSR: {
      TABLE_EMPLOYEE_NAME: 'ui_dsr_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_dsr_search_filter_employee_name',
    },
  },
} as const;

export const UI_PERMISSIONS_ROLE_MAP = {
  SALARY_STRUCTURE: {
    TABLE: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    CONTACT_ANNEXURE: {
      [EUserRole.ADMIN]: false,
      [EUserRole.DRIVER]: true,
      [EUserRole.EMPLOYEE]: true,
      [EUserRole.MANAGER]: false,
      [EUserRole.SUPER_ADMIN]: false,
    },
  },
  COMMON: {
    SIDEBAR_INITIALS: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  ATTENDANCE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  EXPENSE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  FUEL_EXPENSE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  LEAVE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  PAYROLL: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  PROJECT: {
    SEARCH_FILTER_COMPANY_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_CONTRACTOR_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  PROJECT_ANALYSIS: {
    TIMELINE: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    PROFITABILITY: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    DOC: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    DSR: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: true,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  DSR: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  VEHICLE_READING: {
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
} as const satisfies Record<string, Record<string, UIRolePermissionAccess>>;
