import { EUserRole } from '@shared/constants/role.constants';

/** Each UI permission must list every role; use with `UI_PERMISSIONS_ROLE_MAP`. */
export type UIRolePermissionAccess = Record<EUserRole, boolean>;

export const APP_PERMISSION = {
  ANNOUNCEMENT: {
    VIEW_DETAIL: 'announcement.view.detail',
    TABLE_VIEW: 'announcement.view.table',
    CARD_VIEW: 'announcement.view.card',
    ADD: 'announcement.add',
    EDIT: 'announcement.edit',
    DELETE: 'announcement.delete',
  },
  ASSET: {
    VIEW_DETAIL: 'asset.view.detail',
    TABLE_VIEW: 'asset.view.table',
    CARD_VIEW: 'asset.view.card',
    ADD: 'asset.add',
    EDIT: 'asset.edit',
    DELETE: 'asset.delete',
    HANDOVER_INITIATE: 'asset.handover.initiate',
    HANDOVER_ACCEPTED: 'asset.handover.accepted',
    HANDOVER_REJECTED: 'asset.handover.rejected',
    HANDOVER_CANCELLED: 'asset.handover.cancelled',
    DEALLOCATE: 'asset.deallocate',
    EVENT_HISTORY: 'asset.event-history.view.table',
  },
  ATTENDANCE: {
    VIEW_DETAIL: 'attendance.view.detail',
    TABLE_VIEW: 'attendance.view.table',
    CARD_VIEW: 'attendance.view.card',
    APPLY: 'attendance.apply',
    FORCE: 'attendance.force',
    REGULARIZE: 'attendance.regularize',
    APPROVE: 'attendance.approve',
    REJECT: 'attendance.reject',
  },
  COMPANY: {
    VIEW_DETAIL: 'company.view.detail',
    TABLE_VIEW: 'company.view.table',
    CARD_VIEW: 'company.view.card',
    ADD: 'company.add',
    EDIT: 'company.edit',
    DELETE: 'company.delete',
    CHANGE_STATUS: 'company.change-status',
  },
  CONTRACTOR: {
    VIEW_DETAIL: 'contractor.view.detail',
    TABLE_VIEW: 'contractor.view.table',
    CARD_VIEW: 'contractor.view.card',
    ADD: 'contractor.add',
    EDIT: 'contractor.edit',
    DELETE: 'contractor.delete',
    CHANGE_STATUS: 'contractor.change-status',
  },
  VENDOR: {
    VIEW_DETAIL: 'vendor.view.detail',
    TABLE_VIEW: 'vendor.view.table',
    CARD_VIEW: 'vendor.view.card',
    ADD: 'vendor.add',
    EDIT: 'vendor.edit',
    DELETE: 'vendor.delete',
    CHANGE_STATUS: 'vendor.change-status',
  },
  EMPLOYEE: {
    VIEW_DETAIL: 'employee.view.detail',
    TABLE_VIEW: 'employee.view.table',
    CARD_VIEW: 'employee.view.card',
    ADD: 'employee.add',
    EDIT: 'employee.edit',
    DELETE: 'employee.delete',
    CHANGE_STATUS: 'employee.change-status',
    SEND_PASSWORD_LINK: 'employee.send-password-link',
  },
  EXPENSE: {
    VIEW_DETAIL: 'expense.view.detail',
    TABLE_VIEW: 'expense.view.table',
    CARD_VIEW: 'expense.view.card',
    ADD: 'expense.add',
    EDIT: 'expense.edit',
    DELETE: 'expense.delete',
    FORCE: 'expense.force',
    REIMBURSE: 'expense.reimburse',
    APPROVE: 'expense.approve',
    REJECT: 'expense.reject',
  },
  FUEL_EXPENSE: {
    VIEW_DETAIL: 'fuel.view.detail',
    TABLE_VIEW: 'fuel.view.table',
    CARD_VIEW: 'fuel.view.card',
    ADD: 'fuel.add',
    EDIT: 'fuel.edit',
    DELETE: 'fuel.delete',
    FORCE: 'fuel.force',
    REIMBURSE: 'fuel.reimburse',
    APPROVE: 'fuel.approve',
    REJECT: 'fuel.reject',
  },
  LEAVE: {
    VIEW_DETAIL: 'leave.view.detail',
    TABLE_VIEW: 'leave.view.table',
    CARD_VIEW: 'leave.view.card',
    APPLY: 'leave.apply',
    FORCE: 'leave.force',
    APPROVE: 'leave.approve',
    REJECT: 'leave.reject',
    CANCEL: 'leave.cancel',
  },
  PAYROLL: {
    VIEW_DETAIL: 'payroll.view.detail',
    TABLE_VIEW: 'payroll.view.table',
    CARD_VIEW: 'payroll.view.card',
    PAID: 'payroll.payslip.paid',
    GENERATE_PAYSLIP: 'payroll.generate.payslip',
    GENERATE: 'payroll.generate',
    MONTHLY_REPORT: 'payroll.download.monthly-report',
    CANCEL: 'payroll.payslip.cancel',
    APPROVE: 'payroll.payslip.approve',
    ADD_INCREMENT: 'payroll.add-increment',
  },
  PETRO_CARD: {
    TABLE_VIEW: 'petro-card.view.table',
    CARD_VIEW: 'petro-card.view.card',
    ADD: 'petro-card.add',
    EDIT: 'petro-card.edit',
    DELETE: 'petro-card.delete',
    LINK_VEHICLE: 'petro-card.link-vehicle',
    UNLINK_VEHICLE: 'petro-card.unlink-vehicle',
  },
  SALARY_STRUCTURE: {
    VIEW_DETAIL: 'salary-structure.view.detail',
    TABLE_VIEW: 'salary-structure.view.table',
    CARD_VIEW: 'salary-structure.view.card',
    EDIT: 'salary-structure.edit',
  },
  ROLE_PERMISSION: {
    TABLE_VIEW: 'permission.role.view.table',
    CARD_VIEW: 'permission.role.view.card',
    ADD: 'permission.role.add',
    EDIT: 'permission.role.edit',
    DELETE: 'permission.role.delete',
    SET: 'permission.role.set-permission',
  },
  SYSTEM_PERMISSION: {
    TABLE_VIEW: 'permission.system.view.table',
    CARD_VIEW: 'permission.system.view.card',
    ADD: 'permission.system.add',
    EDIT: 'permission.system.edit',
    DELETE: 'permission.system.delete',
    SET: 'permission.system.set-permission',
  },
  USER_PERMISSION: {
    TABLE_VIEW: 'permission.user.view.table',
    CARD_VIEW: 'permission.user.view.card',
    DELETE: 'permission.user.delete',
    SET: 'permission.user.set-permission',
    CHANGE_ROLE: 'permission.user.change-role',
  },
  VEHICLE: {
    VIEW_DETAIL: 'vehicle.view.detail',
    TABLE_VIEW: 'vehicle.view.table',
    CARD_VIEW: 'vehicle.view.card',
    ADD: 'vehicle.add',
    EDIT: 'vehicle.edit',
    DELETE: 'vehicle.delete',
    HANDOVER_INITIATE: 'vehicle.handover.initiate',
    HANDOVER_ACCEPTED: 'vehicle.handover.accepted',
    HANDOVER_REJECTED: 'vehicle.handover.rejected',
    HANDOVER_CANCELLED: 'vehicle.handover.cancelled',
    DEALLOCATE: 'vehicle.deallocate',
    EVENT_HISTORY: 'vehicle.event-history.view.table',
    SERVICE_HISTORY: 'vehicle.service-history',
    LINK_PETRO_CARD: 'vehicle.link-petro-card',
    UNLINK_PETRO_CARD: 'vehicle.unlink-petro-card',
  },
  VEHICLE_READING: {
    VIEW_DETAIL: 'vehicle-reading.view.detail',
    TABLE_VIEW: 'vehicle-reading.view.table',
    CARD_VIEW: 'vehicle-reading.view.card',
    ADD: 'vehicle-reading.add',
    EDIT: 'vehicle-reading.edit',
    FORCE: 'vehicle-reading.force',
  },
  VEHICLE_SERVICE: {
    VIEW_DETAIL: 'vehicle-service.view.detail',
    TABLE_VIEW: 'vehicle-service.view.table',
    CARD_VIEW: 'vehicle-service.view.card',
    ADD: 'vehicle-service.add',
    EDIT: 'vehicle-service.edit',
    DELETE: 'vehicle-service.delete',
  },
  CRON: {
    TABLE_VIEW: 'cron.view.table',
    CARD_VIEW: 'cron.view.card',
    RUN: 'cron.run',
  },
  CONFIGURATION: {
    TABLE_VIEW: 'configuration.view.table',
    CARD_VIEW: 'configuration.view.card',
    ADD: 'configuration.add',
    EDIT: 'configuration.edit',
    DELETE: 'configuration.delete',
  },
  PROJECT: {
    VIEW_DETAIL: 'project.view.detail',
    TABLE_VIEW: 'project.view.table',
    CARD_VIEW: 'project.view.card',
    ADD: 'project.add',
    EDIT: 'project.edit',
    DELETE: 'project.delete',
    CHANGE_STATUS: 'project.change-status',
    WORKSPACE: 'project.analysis',
    ALLOCATE_DEALLOCATE_EMPLOYEE: 'project.allocate-deallocate-employee',
  },
  UI: {
    SALARY_STRUCTURE: {
      TABLE: 'ui_table_salary_structure',
      CONTACT_ANNEXURE: 'ui_contact_annexure_salary_structure',
    },
    COMMON: {
      SIDEBAR_INITIALS: 'ui_common_sidebar_initials',
    },
    ATTENDANCE: {
      TABLE_EMPLOYEE_NAME: 'ui_attendance_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_attendance_search_filter_employee_name',
    },
    EXPENSE: {
      TABLE_EMPLOYEE_NAME: 'ui_expense_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_expense_search_filter_employee_name',
    },
    LEAVE: {
      TABLE_EMPLOYEE_NAME: 'ui_leave_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_leave_search_filter_employee_name',
    },
    FUEL_EXPENSE: {
      TABLE_EMPLOYEE_NAME: 'ui_fuel_expense_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME:
        'ui_fuel_expense_search_filter_employee_name',
    },
    VEHICLE_READING: {
      SEARCH_FILTER_EMPLOYEE_NAME:
        'ui_vehicle_reading_search_filter_employee_name',
    },
    PAYROLL: {
      TABLE_EMPLOYEE_NAME: 'ui_payroll_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_payroll_search_filter_employee_name',
    },
    PROJECT: {
      SEARCH_FILTER_COMPANY_NAME: 'ui_project_search_filter_company_name',
      SEARCH_FILTER_CONTRACTOR_NAME: 'ui_project_search_filter_contractor_name',
    },
    PROJECT_WORKSPACE: {
      TIMELINE: 'ui_project_analysis_timeline',
      PROFITABILITY: 'ui_project_analysis_profitability',
      DOC: 'ui_project_analysis_doc',
      DSR: 'ui_project_analysis_dsr',
    },
    DSR: {
      TABLE_EMPLOYEE_NAME: 'ui_dsr_table_employee_name',
      SEARCH_FILTER_EMPLOYEE_NAME: 'ui_dsr_search_filter_employee_name',
    },
  },
} as const;

export const UI_PERMISSIONS_ROLE_MAP = {
  SALARY_STRUCTURE: {
    TABLE: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    CONTACT_ANNEXURE: {
      [EUserRole.ADMIN]: false,
      [EUserRole.DRIVER]: true,
      [EUserRole.EMPLOYEE]: true,
      [EUserRole.MANAGER]: false,
      [EUserRole.SUPER_ADMIN]: false,
    },
  },
  COMMON: {
    SIDEBAR_INITIALS: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  ATTENDANCE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  EXPENSE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  FUEL_EXPENSE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  LEAVE: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  PAYROLL: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  PROJECT: {
    SEARCH_FILTER_COMPANY_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_CONTRACTOR_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  PROJECT_WORKSPACE: {
    TIMELINE: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    PROFITABILITY: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    DOC: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    DSR: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: true,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  DSR: {
    TABLE_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
  VEHICLE_READING: {
    SEARCH_FILTER_EMPLOYEE_NAME: {
      [EUserRole.ADMIN]: true,
      [EUserRole.DRIVER]: false,
      [EUserRole.EMPLOYEE]: false,
      [EUserRole.MANAGER]: true,
      [EUserRole.SUPER_ADMIN]: true,
    },
  },
} as const satisfies Record<string, Record<string, UIRolePermissionAccess>>;
