export const APP_PERMISSION = {
  ANNOUNCEMENT: {
    MODULE: 'module_announcement',
    VIEW_DETAIL: 'view_detail_announcement',
    TABLE_VIEW: 'table_view_announcement',
    CARD_VIEW: 'card_view_announcement',
    ADD: 'add_announcement',
    EDIT: 'edit_announcement',
    DELETE: 'delete_announcement',
  },
  ASSET: {
    MODULE: 'module_asset',
    VIEW_DETAIL: 'view_detail_asset',
    TABLE_VIEW: 'table_view_asset',
    CARD_VIEW: 'card_view_asset',
    ADD: 'add_asset',
    EDIT: 'edit_asset',
    DELETE: 'delete_asset',
    HANDOVER_INITIATE: 'handover_initiate_asset',
    HANDOVER_ACCEPTED: 'handover_accepted_asset',
    HANDOVER_REJECTED: 'handover_rejected_asset',
    HANDOVER_CANCELLED: 'handover_cancelled_asset',
    DEALLOCATE: 'deallocate_asset',
    EVENT_HISTORY: 'event_history_asset',
  },
  ATTENDANCE: {
    MODULE: 'module_attendance',
    VIEW_DETAIL: 'view_detail_attendance',
    TABLE_VIEW: 'table_view_attendance',
    CARD_VIEW: 'card_view_attendance',
    APPLY: 'apply_attendance',
    FORCE: 'force_attendance',
    REGULARIZE: 'regularize_attendance',
    APPROVE: 'approve_attendance',
    REJECT: 'reject_attendance',
  },
  COMPANY: {
    MODULE: 'module_company',
    VIEW_DETAIL: 'view_detail_company',
    TABLE_VIEW: 'table_view_company',
    CARD_VIEW: 'card_view_company',
    ADD: 'add_company',
    EDIT: 'edit_company',
    DELETE: 'delete_company',
    CHANGE_STATUS: 'change_status_company',
  },
  CONTRACTOR: {
    MODULE: 'module_contractor',
    VIEW_DETAIL: 'view_detail_contractor',
    TABLE_VIEW: 'table_view_contractor',
    CARD_VIEW: 'card_view_contractor',
    ADD: 'add_contractor',
    EDIT: 'edit_contractor',
    DELETE: 'delete_contractor',
    CHANGE_STATUS: 'change_status_contractor',
  },
  EMPLOYEE: {
    MODULE: 'module_employee',
    VIEW_DETAIL: 'view_detail_employee',
    TABLE_VIEW: 'table_view_employee',
    CARD_VIEW: 'card_view_employee',
    ADD: 'add_employee',
    EDIT: 'edit_employee',
    DELETE: 'delete_employee',
    CHANGE_STATUS: 'change_status_employee',
    SEND_PASSWORD_LINK: 'send_password_link_employee',
  },
  EXPENSE: {
    MODULE: 'module_expense',
    VIEW_DETAIL: 'view_detail_expense',
    TABLE_VIEW: 'table_view_expense',
    CARD_VIEW: 'card_view_expense',
    ADD: 'add_expense',
    EDIT: 'edit_expense',
    DELETE: 'delete_expense',
    FORCE: 'force_expense',
    REIMBURSE: 'reimburse_expense',
    APPROVE: 'approve_expense',
    REJECT: 'reject_expense',
  },
  FUEL_EXPENSE: {
    MODULE: 'module_fuel_expense',
    VIEW_DETAIL: 'view_detail_fuel_expense',
    TABLE_VIEW: 'table_view_fuel_expense',
    CARD_VIEW: 'card_view_fuel_expense',
    ADD: 'add_fuel_expense',
    EDIT: 'edit_fuel_expense',
    DELETE: 'delete_fuel_expense',
    FORCE: 'force_fuel_expense',
    REIMBURSE: 'reimburse_fuel_expense',
    APPROVE: 'approve_fuel_expense',
    REJECT: 'reject_fuel_expense',
  },
  LEAVE: {
    MODULE: 'module_leave',
    VIEW_DETAIL: 'view_detail_leave',
    TABLE_VIEW: 'table_view_leave',
    CARD_VIEW: 'card_view_leave',
    APPLY: 'apply_leave',
    FORCE: 'force_leave',
    APPROVE: 'approve_leave',
    REJECT: 'reject_leave',
    CANCEL: 'cancel_leave',
  },
  PAYROLL: {
    MODULE: 'module_payroll',
    VIEW_DETAIL: 'view_detail_payroll',
    TABLE_VIEW: 'table_view_payroll',
    CARD_VIEW: 'card_view_payroll',
    PAID: 'paid_payslip_payroll',
    GENERATE_PAYSLIP: 'generate_payslip_payroll',
    GENERATE: 'generate_payroll_payroll',
    MONTHLY_REPORT: 'download_monthly_report_payroll',
    CANCEL: 'cancel_payslip_payroll',
    APPROVE: 'approve_payslip_payroll',
    ADD_INCREMENT: 'add_increment_payroll',
  },
  PETRO_CARD: {
    MODULE: 'module_petro_card',
    TABLE_VIEW: 'table_view_petro_card',
    CARD_VIEW: 'card_view_petro_card',
    ADD: 'add_petro_card',
    EDIT: 'edit_petro_card',
    DELETE: 'delete_petro_card',
    LINK_VEHICLE: 'link_vehicle_petro_card',
    UNLINK_VEHICLE: 'unlink_vehicle_petro_card',
  },
  PROJECT: {
    MODULE: 'module_project',
    VIEW_DETAIL: 'view_detail_project',
    TABLE_VIEW: 'table_view_project',
    CARD_VIEW: 'card_view_project',
    ADD: 'add_project',
    EDIT: 'edit_project',
    DELETE: 'delete_project',
    CHANGE_STATUS: 'change_status_project',
    ANALYSIS: 'analysis_project',
  },
  ROLE_PERMISSION: {
    MODULE: 'module_role_permission',
    TABLE_VIEW: 'table_view_role_permission',
    CARD_VIEW: 'card_view_role_permission',
    ADD: 'add_role_permission',
    EDIT: 'edit_role_permission',
    DELETE: 'delete_role_permission',
    SET: 'set_permission_role_permission',
  },
  SALARY_STRUCTURE: {
    MODULE: 'module_salary_structure',
    VIEW_DETAIL: 'view_detail_salary_structure',
    TABLE_VIEW: 'table_view_salary_structure',
    CARD_VIEW: 'card_view_salary_structure',
    EDIT: 'edit_salary_structure',
  },
  SYSTEM_PERMISSION: {
    MODULE: 'module_system_permission',
    TABLE_VIEW: 'table_view_system_permission',
    CARD_VIEW: 'card_view_system_permission',
    ADD: 'add_system_permission',
    EDIT: 'edit_system_permission',
    DELETE: 'delete_system_permission',
    SET: 'set_permission_system_permission',
  },
  USER_PERMISSION: {
    MODULE: 'module_user_permission',
    TABLE_VIEW: 'table_view_user_permission',
    CARD_VIEW: 'card_view_user_permission',
    DELETE: 'delete_user_permission',
    SET: 'set_permission_user_permission',
    CHANGE_ROLE: 'change_role_user_permission',
  },
  VEHICLE: {
    MODULE: 'module_vehicle',
    VIEW_DETAIL: 'view_detail_vehicle',
    TABLE_VIEW: 'table_view_vehicle',
    CARD_VIEW: 'card_view_vehicle',
    ADD: 'add_vehicle',
    EDIT: 'edit_vehicle',
    DELETE: 'delete_vehicle',
    HANDOVER_INITIATE: 'handover_initiate_vehicle',
    HANDOVER_ACCEPTED: 'handover_accepted_vehicle',
    HANDOVER_REJECTED: 'handover_rejected_vehicle',
    HANDOVER_CANCELLED: 'handover_cancelled_vehicle',
    DEALLOCATE: 'deallocate_vehicle',
    EVENT_HISTORY: 'event_history_vehicle',
    SERVICE_HISTORY: 'service_history_vehicle',
    LINK_PETRO_CARD: 'link_petro_card_vehicle',
    UNLINK_PETRO_CARD: 'unlink_petro_card_vehicle',
  },
  VEHICLE_READING: {
    MODULE: 'module_vehicle_reading',
    VIEW_DETAIL: 'view_detail_vehicle_reading',
    TABLE_VIEW: 'table_view_vehicle_reading',
    CARD_VIEW: 'card_view_vehicle_reading',
    ADD: 'add_vehicle_reading',
    EDIT: 'edit_vehicle_reading',
    FORCE: 'force_vehicle_reading',
  },
  VEHICLE_SERVICE: {
    MODULE: 'module_vehicle_service',
    VIEW_DETAIL: 'view_detail_vehicle_service',
    TABLE_VIEW: 'table_view_vehicle_service',
    CARD_VIEW: 'card_view_vehicle_service',
    ADD: 'add_vehicle_service',
    EDIT: 'edit_vehicle_service',
    DELETE: 'delete_vehicle_service',
  },
  UI: {
    SALARY_STRUCTURE: {
      TABLE: 'ui_table_salary_structure',
      CONTACT_ANNEXURE: 'ui_contact_annexure_salary_structure',
    },
    COMMON: {
      SIDEBAR_INITIALS: 'ui_common_sidebar_initials',
    },
  },
} as const;

export const UI_PERMISSIONS_ROLE_MAP = {
  SALARY_STRUCTURE: {
    TABLE: {
      ADMIN: true,
      DRIVER: false,
    },
    CONTACT_ANNEXURE: {
      ADMIN: false,
      DRIVER: true,
    },
  },
  COMMON: {
    SIDEBAR_INITIALS: {
      ADMIN: true,
      DRIVER: false,
    },
  },
} as const;
