export const STATUS_COLOR_GROUPS: Record<string, string[]> = {
  success: [
    'active',
    'approved',
    'approve',
    'present',
    'clearselection',
    'download',
    'submit',
    'filter',
    'pageheaderbutton1',
    'checkin',
    'total credit',
    'period credit',
    'total credited',
    'active employees',
  ],
  danger: [
    'inactive',
    'rejected',
    'reject',
    'absent',
    'delete',
    'checkout',
    'closing balance',
    'total debit',
    'period debit',
    'total consumed',
    'inactive employees',
  ],
  warning: [
    'pending',
    'leave',
    'regularize',
    'edit',
    'pageheaderbutton2',
    'cancel',
    'cancelled',
    'new joiners last 30 days',
  ],
  info: [
    'holiday',
    'view',
    'setpermissions',
    'total',
    'opening balance',
    'total balance',
    'total employees',
    'male',
    'female',
  ],
};
